//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "balance_entry")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub balance_id: i32,
    pub raw_currency: String,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub amount: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::balance::Entity",
        from = "Column::BalanceId",
        to = "super::balance::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Balance,
}

impl Related<super::balance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Balance.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
