//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "currency")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::currency_map::Entity")]
    CurrencyMap,
    #[sea_orm(has_many = "super::price_provider::Entity")]
    PriceProvider,
}

impl Related<super::currency_map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CurrencyMap.def()
    }
}

impl Related<super::price_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PriceProvider.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
