//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use super::sea_orm_active_enums::DataProvider;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "price")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub currency: String,
    pub time: TimeDateTimeWithTimeZone,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub value: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub liquidity: Decimal,
    pub provider: DataProvider,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
