//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "asset_scope")]
pub enum AssetScope {
    #[sea_orm(string_value = "binance")]
    Binance,
    #[sea_orm(string_value = "upbit")]
    Upbit,
    #[sea_orm(string_value = "spot")]
    Spot,
    #[sea_orm(string_value = "future")]
    Future,
    #[sea_orm(string_value = "ethereum")]
    Ethereum,
    #[sea_orm(string_value = "pendle2")]
    Pendle2,
    #[sea_orm(string_value = "stakestone")]
    Stakestone,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "data_provider")]
pub enum DataProvider {
    #[sea_orm(string_value = "cam")]
    Cam,
    #[sea_orm(string_value = "ccxt")]
    Ccxt,
    #[sea_orm(string_value = "debank")]
    Debank,
}
